-- Migration 001: Initial Schema - All Core Tables
-- Applied by: DatabaseInitializer / MigrationRunner
-- Description: Creates all master data, transaction, inventory, purchase, and system tables

-- Master Data Tables
CREATE TABLE IF NOT EXISTS Categories (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(200) NOT NULL,
    Description VARCHAR(500) NULL,
    DisplayOrder INT DEFAULT 0,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Units (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Symbol VARCHAR(20) NULL,
    DisplayOrder INT DEFAULT 0,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `Groups` (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(200) NOT NULL,
    Description VARCHAR(500) NULL,
    ParentGroupId INT NULL,
    DisplayOrder INT DEFAULT 0,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_Groups_ParentGroup FOREIGN KEY (ParentGroupId) REFERENCES `Groups`(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Currencies (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(10) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Symbol VARCHAR(10) NULL,
    ExchangeRate DECIMAL(18,6) DEFAULT 1.0,
    IsActive BOOLEAN DEFAULT 1,
    IsDefault BOOLEAN DEFAULT 0,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Taxes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Rate DECIMAL(18,4) NOT NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    DisplayOrder INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Discounts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Rate DECIMAL(18,4) NOT NULL,
    MinimumAmount DECIMAL(18,2) NULL,
    MaximumAmount DECIMAL(18,2) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    DisplayOrder INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Locations (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(200) NOT NULL,
    Address VARCHAR(300) NULL,
    City VARCHAR(100) NULL,
    Phone VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsHeadquarter BOOLEAN DEFAULT 0,
    IsDeleted BOOLEAN DEFAULT 0,
    DisplayOrder INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Companies (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(200) NOT NULL,
    RegistrationNumber VARCHAR(100) NULL,
    TaxId VARCHAR(50) NULL,
    Address VARCHAR(300) NULL,
    City VARCHAR(100) NULL,
    Country VARCHAR(100) NULL,
    Phone VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    Website VARCHAR(200) NULL,
    LogoPath VARCHAR(300) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(300) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    FullName VARCHAR(200) NOT NULL,
    Phone VARCHAR(20) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    LastLoginAt DATETIME NULL,
    LocationId INT NULL,
    CompanyId INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_Users_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE SET NULL,
    CONSTRAINT FK_Users_Company FOREIGN KEY (CompanyId) REFERENCES Companies(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Roles (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(500) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS UserRoles (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    RoleId INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_UserRoles_User FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT FK_UserRoles_Role FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE,
    CONSTRAINT UQ_UserRole UNIQUE (UserId, RoleId)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MenuRoles (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    RoleId INT NOT NULL,
    MenuCode VARCHAR(100) NOT NULL,
    CanView BOOLEAN DEFAULT 0,
    CanCreate BOOLEAN DEFAULT 0,
    CanEdit BOOLEAN DEFAULT 0,
    CanDelete BOOLEAN DEFAULT 0,
    CanExport BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_MenuRoles_Role FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE,
    CONSTRAINT UQ_RoleMenu UNIQUE (RoleId, MenuCode)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS EmailSettings (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SmtpHost VARCHAR(200) NOT NULL,
    SmtpPort INT DEFAULT 587,
    SmtpUsername VARCHAR(200) NOT NULL,
    SmtpPassword VARCHAR(300) NOT NULL,
    FromAddress VARCHAR(100) NOT NULL,
    FromName VARCHAR(200) NOT NULL,
    EnableTls BOOLEAN DEFAULT 1,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Suppliers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(200) NOT NULL,
    Address VARCHAR(300) NULL,
    City VARCHAR(100) NULL,
    Country VARCHAR(100) NULL,
    Phone VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    ContactPerson VARCHAR(200) NULL,
    TaxId VARCHAR(50) NULL,
    CreditLimit DECIMAL(18,2) NULL,
    PaymentTermDays INT DEFAULT 0,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Sales Tables
CREATE TABLE IF NOT EXISTS Products (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Sku VARCHAR(50) NOT NULL,
    Name VARCHAR(200) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    StockQuantity INT NOT NULL,
    IsActive BOOLEAN DEFAULT 1,
    MinStockAlertLevel INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Customers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(20) NOT NULL UNIQUE,
    Name VARCHAR(150) NOT NULL,
    Address VARCHAR(200) NULL,
    Phone VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SaleTemps (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CustomerId INT NULL,
    CustomerName VARCHAR(150) NULL,
    CustomerPhone VARCHAR(20) NULL,
    SaleDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18,2) DEFAULT 0,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    NetAmount DECIMAL(18,2) DEFAULT 0,
    Status VARCHAR(50) DEFAULT 'Draft',
    CreatedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    LocationId INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SaleTemps_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE SET NULL,
    CONSTRAINT FK_SaleTemps_User FOREIGN KEY (CreatedByUserId) REFERENCES Users(Id) ON DELETE SET NULL,
    CONSTRAINT FK_SaleTemps_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SaleTempDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SaleTempId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    LineTotal DECIMAL(18,2) NOT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SaleTempDetails_SaleTemp FOREIGN KEY (SaleTempId) REFERENCES SaleTemps(Id) ON DELETE CASCADE,
    CONSTRAINT FK_SaleTempDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Sales (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CustomerId INT NOT NULL,
    SaleDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    Status VARCHAR(50) NULL,
    LocationId INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_Sales_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SaleDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SaleId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SaleDetails_Sale FOREIGN KEY (SaleId) REFERENCES Sales(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_SaleDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Inventory & Warehouse Tables
CREATE TABLE IF NOT EXISTS StockMovements (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    MovementNo VARCHAR(50) NOT NULL,
    MovementType VARCHAR(50) NOT NULL,
    MovementDate DATETIME NOT NULL,
    LocationId INT NULL,
    SupplierId INT NULL,
    CustomerId INT NULL,
    Reason VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StockMovements_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE SET NULL,
    CONSTRAINT FK_StockMovements_Supplier FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id) ON DELETE SET NULL,
    CONSTRAINT FK_StockMovements_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StockMovementDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    StockMovementId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitCost DECIMAL(18,2) NOT NULL,
    LineTotal DECIMAL(18,2) NOT NULL,
    SerialNumber VARCHAR(50) NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StockMovementDetails_Movement FOREIGN KEY (StockMovementId) REFERENCES StockMovements(Id) ON DELETE CASCADE,
    CONSTRAINT FK_StockMovementDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Assemblies (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    AssemblyNo VARCHAR(50) NOT NULL,
    OutputProductId INT NOT NULL,
    OutputQuantity INT NOT NULL,
    AssemblyDate DATETIME NOT NULL,
    TotalCost DECIMAL(18,2) DEFAULT 0,
    LocationId INT NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_Assemblies_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS AssemblyDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    AssemblyId INT NOT NULL,
    ComponentProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitCost DECIMAL(18,2) NOT NULL,
    LineTotal DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_AssemblyDetails_Assembly FOREIGN KEY (AssemblyId) REFERENCES Assemblies(Id) ON DELETE CASCADE,
    CONSTRAINT FK_AssemblyDetails_Product FOREIGN KEY (ComponentProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SalePriceHistories (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ProductId INT NOT NULL,
    OldPrice DECIMAL(18,2) NOT NULL,
    NewPrice DECIMAL(18,2) NOT NULL,
    EffectiveDate DATETIME NOT NULL,
    ChangedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SalePriceHistories_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS LinkedStocks (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    PrimaryProductId INT NOT NULL,
    LinkedProductId INT NOT NULL,
    Quantity INT DEFAULT 1,
    LinkType VARCHAR(50) NOT NULL DEFAULT 'Related',
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_LinkedStocks_PrimaryProduct FOREIGN KEY (PrimaryProductId) REFERENCES Products(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_LinkedStocks_LinkedProduct FOREIGN KEY (LinkedProductId) REFERENCES Products(Id) ON DELETE RESTRICT,
    CONSTRAINT UQ_LinkedStock UNIQUE (PrimaryProductId, LinkedProductId)
) ENGINE=InnoDB;

-- Purchase Tables
CREATE TABLE IF NOT EXISTS Purchases (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    InvoiceNo VARCHAR(50) NOT NULL UNIQUE,
    SupplierId INT NOT NULL,
    PurchaseDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18,2) DEFAULT 0,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    NetAmount DECIMAL(18,2) DEFAULT 0,
    PaidAmount DECIMAL(18,2) DEFAULT 0,
    Status VARCHAR(50) DEFAULT 'Active',
    LocationId INT NULL,
    CreatedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_Purchases_Supplier FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_Purchases_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PurchaseDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    PurchaseId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    LineTotal DECIMAL(18,2) NOT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_PurchaseDetails_Purchase FOREIGN KEY (PurchaseId) REFERENCES Purchases(Id) ON DELETE CASCADE,
    CONSTRAINT FK_PurchaseDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PurchaseReturns (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ReturnNo VARCHAR(50) NOT NULL UNIQUE,
    PurchaseId INT NOT NULL,
    SupplierId INT NOT NULL,
    ReturnDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18,2) DEFAULT 0,
    Reason VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_PurchaseReturns_Purchase FOREIGN KEY (PurchaseId) REFERENCES Purchases(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_PurchaseReturns_Supplier FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PurchaseReturnDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    PurchaseReturnId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    LineTotal DECIMAL(18,2) NOT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_PurchaseReturnDetails_Return FOREIGN KEY (PurchaseReturnId) REFERENCES PurchaseReturns(Id) ON DELETE CASCADE,
    CONSTRAINT FK_PurchaseReturnDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- Outstanding & Payment Tables
CREATE TABLE IF NOT EXISTS CustomerOutstandings (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    CustomerId INT NOT NULL,
    SaleId INT NULL,
    TransactionDate DATETIME NOT NULL,
    DebitAmount DECIMAL(18,2) DEFAULT 0,
    CreditAmount DECIMAL(18,2) DEFAULT 0,
    Balance DECIMAL(18,2) DEFAULT 0,
    Description VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Open',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_CustomerOutstandings_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_CustomerOutstandings_Sale FOREIGN KEY (SaleId) REFERENCES Sales(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SupplierOutstandings (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SupplierId INT NOT NULL,
    PurchaseId INT NULL,
    TransactionDate DATETIME NOT NULL,
    DebitAmount DECIMAL(18,2) DEFAULT 0,
    CreditAmount DECIMAL(18,2) DEFAULT 0,
    Balance DECIMAL(18,2) DEFAULT 0,
    Description VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Open',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SupplierOutstandings_Supplier FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_SupplierOutstandings_Purchase FOREIGN KEY (PurchaseId) REFERENCES Purchases(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Payments (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    PaymentNo VARCHAR(50) NOT NULL UNIQUE,
    PaymentType VARCHAR(50) NOT NULL DEFAULT 'Customer',
    CustomerId INT NULL,
    SupplierId INT NULL,
    SaleId INT NULL,
    PurchaseId INT NULL,
    PaymentDate DATETIME NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Method VARCHAR(50) NOT NULL DEFAULT 'Cash',
    ReferenceNo VARCHAR(100) NULL,
    BankName VARCHAR(200) NULL,
    ChequeNo VARCHAR(50) NULL,
    ChequeDate DATETIME NULL,
    Status VARCHAR(50) DEFAULT 'Cleared',
    ReceivedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_Payments_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE SET NULL,
    CONSTRAINT FK_Payments_Supplier FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Expense Tables
CREATE TABLE IF NOT EXISTS ExpenseTypes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(500) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    DisplayOrder INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Expenses (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ExpenseNo VARCHAR(50) NOT NULL UNIQUE,
    ExpenseTypeId INT NOT NULL,
    ExpenseDate DATETIME NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentMethod VARCHAR(50) NOT NULL DEFAULT 'Cash',
    ReferenceNo VARCHAR(100) NULL,
    VendorId INT NULL,
    LocationId INT NULL,
    ReceiptPath VARCHAR(300) NULL,
    Description VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_Expenses_ExpenseType FOREIGN KEY (ExpenseTypeId) REFERENCES ExpenseTypes(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_Expenses_Vendor FOREIGN KEY (VendorId) REFERENCES Suppliers(Id) ON DELETE SET NULL,
    CONSTRAINT FK_Expenses_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Invoices & Sales Returns
CREATE TABLE IF NOT EXISTS Invoices (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    InvoiceNo VARCHAR(50) NOT NULL UNIQUE,
    SaleId INT NOT NULL,
    CustomerId INT NOT NULL,
    InvoiceDate DATETIME NOT NULL,
    AmountDue DECIMAL(18,2) NOT NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_Invoices_Sale FOREIGN KEY (SaleId) REFERENCES Sales(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_Invoices_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SalesReturns (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ReturnNo VARCHAR(50) NOT NULL UNIQUE,
    SaleId INT NOT NULL,
    CustomerId INT NOT NULL,
    ReturnDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18,2) DEFAULT 0,
    Reason VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SalesReturns_Sale FOREIGN KEY (SaleId) REFERENCES Sales(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_SalesReturns_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SalesReturnDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SalesReturnId INT NOT NULL,
    SaleDetailId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    Reason VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SalesReturnDetails_Return FOREIGN KEY (SalesReturnId) REFERENCES SalesReturns(Id) ON DELETE CASCADE,
    CONSTRAINT FK_SalesReturnDetails_SaleDetail FOREIGN KEY (SaleDetailId) REFERENCES SaleDetails(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_SalesReturnDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- License & Update Tables
CREATE TABLE IF NOT EXISTS LicenseInfos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    LicenseKey VARCHAR(100) NOT NULL UNIQUE,
    CompanyName VARCHAR(200) NOT NULL,
    ContactPerson VARCHAR(100) NULL,
    Email VARCHAR(100) NULL,
    Phone VARCHAR(20) NULL,
    Address VARCHAR(300) NULL,
    RegistrationDate DATETIME NOT NULL,
    ExpiryDate DATETIME NOT NULL,
    MaxUsers INT DEFAULT 1,
    MaxDevices INT DEFAULT 1,
    Status VARCHAR(50) DEFAULT 'Active',
    Notes VARCHAR(500) NULL,
    IsActivated BOOLEAN DEFAULT 0,
    ActivatedDate DATETIME NULL,
    ActivatedDeviceId VARCHAR(200) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DeviceInfos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    RegistrationId INT NULL,
    DeviceFingerprint VARCHAR(200) NOT NULL,
    DeviceName VARCHAR(100) NULL,
    MacAddress VARCHAR(50) NULL,
    CpuId VARCHAR(100) NULL,
    HardDiskSerial VARCHAR(100) NULL,
    OsVersion VARCHAR(50) NULL,
    LastSeenAt DATETIME NULL,
    IsActive BOOLEAN DEFAULT 1,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    INDEX IX_DeviceInfos_Fingerprint (DeviceFingerprint)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DeviceRequests (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DeviceId VARCHAR(200) NOT NULL,
    DeviceName VARCHAR(100) NULL,
    DeviceFingerprint VARCHAR(200) NOT NULL,
    MacAddress VARCHAR(50) NULL,
    CpuId VARCHAR(100) NULL,
    HardDiskSerial VARCHAR(100) NULL,
    OsVersion VARCHAR(50) NULL,
    LicenseKey VARCHAR(100) NULL,
    Status VARCHAR(50) DEFAULT 'Pending',
    RequestType VARCHAR(50) NULL,
    ApprovedByUserId INT NULL,
    ProcessedDate DATETIME NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PcClients (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DeviceId VARCHAR(200) NOT NULL,
    DeviceName VARCHAR(100) NULL,
    LicenseKey VARCHAR(100) NULL,
    MacAddress VARCHAR(50) NULL,
    CpuId VARCHAR(100) NULL,
    HardDiskSerial VARCHAR(100) NULL,
    OsVersion VARCHAR(50) NULL,
    AppVersion VARCHAR(50) NULL,
    LastSyncDate DATETIME NULL,
    LastHeartbeat DATETIME NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    IpAddress VARCHAR(50) NULL,
    UserId INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MobileClients (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DeviceId VARCHAR(200) NOT NULL,
    DeviceName VARCHAR(100) NULL,
    LicenseKey VARCHAR(100) NULL,
    DeviceModel VARCHAR(100) NULL,
    OsVersion VARCHAR(50) NULL,
    AppVersion VARCHAR(50) NULL,
    LastSyncDate DATETIME NULL,
    LastHeartbeat DATETIME NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    PushToken VARCHAR(200) NULL,
    UserId INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS AppInfos (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    AppName VARCHAR(100) NOT NULL,
    Version VARCHAR(50) NOT NULL,
    BuildNumber VARCHAR(50) NULL,
    ReleaseNotes VARCHAR(1000) NULL,
    DownloadUrl VARCHAR(500) NULL,
    IsMandatory BOOLEAN DEFAULT 0,
    ReleaseDate DATETIME NOT NULL,
    Platform VARCHAR(50) NULL,
    MinimumOsVersion VARCHAR(50) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PCUpdates (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Version VARCHAR(50) NOT NULL,
    FileName VARCHAR(200) NOT NULL,
    DownloadUrl VARCHAR(500) NOT NULL,
    Checksum VARCHAR(100) NOT NULL,
    FileSize BIGINT NOT NULL,
    ReleaseNotes VARCHAR(1000) NULL,
    IsMandatory BOOLEAN DEFAULT 0,
    ReleaseDate DATETIME NOT NULL,
    MinimumVersion VARCHAR(50) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ClientUpdateRequests (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DeviceId VARCHAR(200) NOT NULL,
    DeviceType VARCHAR(50) NOT NULL,
    CurrentVersion VARCHAR(50) NOT NULL,
    RequestedVersion VARCHAR(50) NULL,
    DeviceInfo VARCHAR(1000) NULL,
    IpAddress VARCHAR(50) NULL,
    Status VARCHAR(50) DEFAULT 'Pending',
    ApprovedByUserId INT NULL,
    ProcessedDate DATETIME NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0
) ENGINE=InnoDB;

-- Starman / Multi-site Tables
CREATE TABLE IF NOT EXISTS StarStockTransferReceiveds (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    TransferNo VARCHAR(50) NOT NULL UNIQUE,
    FromLocationId INT NOT NULL,
    ToLocationId INT NOT NULL,
    TransferDate DATETIME NOT NULL,
    ReceivedDate DATETIME NULL,
    Status VARCHAR(50) DEFAULT 'Pending',
    ReceivedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StarStockTransferReceiveds_FromLocation FOREIGN KEY (FromLocationId) REFERENCES Locations(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_StarStockTransferReceiveds_ToLocation FOREIGN KEY (ToLocationId) REFERENCES Locations(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StarSalePriceTransfers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    TransferNo VARCHAR(50) NOT NULL UNIQUE,
    FromLocationId INT NOT NULL,
    ToLocationId INT NOT NULL,
    TransferDate DATETIME NOT NULL,
    AcceptedDate DATETIME NULL,
    Status VARCHAR(50) DEFAULT 'Pending',
    AcceptedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StarSalePriceTransfers_FromLocation FOREIGN KEY (FromLocationId) REFERENCES Locations(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_StarSalePriceTransfers_ToLocation FOREIGN KEY (ToLocationId) REFERENCES Locations(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StarCashFlowReports (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    LocationId INT NOT NULL,
    ReportDate DATETIME NOT NULL,
    OpeningBalance DECIMAL(18,2) DEFAULT 0,
    TotalSales DECIMAL(18,2) DEFAULT 0,
    TotalPurchases DECIMAL(18,2) DEFAULT 0,
    TotalExpenses DECIMAL(18,2) DEFAULT 0,
    TotalCollections DECIMAL(18,2) DEFAULT 0,
    TotalPayments DECIMAL(18,2) DEFAULT 0,
    ClosingBalance DECIMAL(18,2) DEFAULT 0,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StarCashFlowReports_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StarProfitLossReports (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    LocationId INT NOT NULL,
    FromDate DATETIME NOT NULL,
    ToDate DATETIME NOT NULL,
    TotalRevenue DECIMAL(18,2) DEFAULT 0,
    CostOfGoodsSold DECIMAL(18,2) DEFAULT 0,
    GrossProfit DECIMAL(18,2) DEFAULT 0,
    OperatingExpenses DECIMAL(18,2) DEFAULT 0,
    NetProfit DECIMAL(18,2) DEFAULT 0,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StarProfitLossReports_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StarStockBalanceReports (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    LocationId INT NOT NULL,
    ProductId INT NOT NULL,
    ProductName VARCHAR(200) NOT NULL,
    QuantityOnHand INT DEFAULT 0,
    QuantityReserved INT DEFAULT 0,
    QuantityAvailable INT DEFAULT 0,
    UnitCost DECIMAL(18,2) DEFAULT 0,
    TotalValue DECIMAL(18,2) DEFAULT 0,
    LastMovementDate DATETIME NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StarStockBalanceReports_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_StarStockBalanceReports_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StarReorderReports (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    LocationId INT NOT NULL,
    ProductId INT NOT NULL,
    ProductName VARCHAR(200) NOT NULL,
    CurrentStock INT DEFAULT 0,
    ReorderLevel INT DEFAULT 0,
    ReorderQuantity INT DEFAULT 0,
    SupplierName VARCHAR(200) NULL,
    DaysOfStock INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StarReorderReports_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_StarReorderReports_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StarOutstandingReports (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    LocationId INT NOT NULL,
    PartyType VARCHAR(50) NOT NULL,
    PartyId INT NOT NULL,
    PartyName VARCHAR(200) NOT NULL,
    OpeningBalance DECIMAL(18,2) DEFAULT 0,
    TotalDebit DECIMAL(18,2) DEFAULT 0,
    TotalCredit DECIMAL(18,2) DEFAULT 0,
    ClosingBalance DECIMAL(18,2) DEFAULT 0,
    AsOfDate DATETIME NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StarOutstandingReports_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS IssueHeaders (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    IssueNo VARCHAR(50) NOT NULL UNIQUE,
    FromLocationId INT NOT NULL,
    ToLocationId INT NOT NULL,
    IssueDate DATETIME NOT NULL,
    ReceivedDate DATETIME NULL,
    Status VARCHAR(50) DEFAULT 'Pending',
    IssueType VARCHAR(50) NULL,
    Reason VARCHAR(500) NULL,
    IssuedByUserId INT NULL,
    ReceivedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_IssueHeaders_FromLocation FOREIGN KEY (FromLocationId) REFERENCES Locations(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_IssueHeaders_ToLocation FOREIGN KEY (ToLocationId) REFERENCES Locations(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- Report Menus Table
CREATE TABLE IF NOT EXISTS ReportMenus (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(200) NOT NULL,
    ParentCode VARCHAR(50) NULL,
    FormName VARCHAR(200) NULL,
    AssemblyName VARCHAR(200) NULL,
    IconName VARCHAR(100) NULL,
    DisplayOrder INT DEFAULT 0,
    IsVisible BOOLEAN DEFAULT 1,
    IsReport BOOLEAN DEFAULT 0,
    ReportFileName VARCHAR(200) NULL,
    Description VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0
) ENGINE=InnoDB;

-- Settings Tables
CREATE TABLE IF NOT EXISTS Themes (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(200) NOT NULL,
    Description VARCHAR(500) NULL,
    PrimaryColor VARCHAR(50) DEFAULT '#0078D4',
    SecondaryColor VARCHAR(50) DEFAULT '#E0E0E0',
    AccentColor VARCHAR(50) DEFAULT '#FF6B35',
    BackgroundColor VARCHAR(50) DEFAULT '#FFFFFF',
    TextColor VARCHAR(50) DEFAULT '#333333',
    FontFamily VARCHAR(100) DEFAULT 'Segoe UI',
    FontSize VARCHAR(20) DEFAULT '12pt',
    IsDefault BOOLEAN DEFAULT 0,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Languages (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(10) NOT NULL UNIQUE,
    Name VARCHAR(100) NOT NULL,
    NativeName VARCHAR(100) NOT NULL,
    CultureCode VARCHAR(20) NULL,
    FlagIcon VARCHAR(200) NULL,
    IsDefault BOOLEAN DEFAULT 0,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    DisplayOrder INT DEFAULT 0,
    IsRTL BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Audit Log Tables
CREATE TABLE IF NOT EXISTS ChangeDateLogs (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    EntityName VARCHAR(100) NOT NULL,
    EntityId INT NOT NULL,
    Action VARCHAR(50) NOT NULL,
    OldValues JSON NULL,
    NewValues JSON NULL,
    ChangedByUserId INT NULL,
    ChangedByUserName VARCHAR(200) NULL,
    Description VARCHAR(500) NULL,
    IpAddress VARCHAR(50) DEFAULT '',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IX_ChangeDateLogs_Entity (EntityName, EntityId),
    INDEX IX_ChangeDateLogs_User (ChangedByUserId),
    INDEX IX_ChangeDateLogs_Date (CreatedAt)
) ENGINE=InnoDB;

-- System Settings & Backup Tables
CREATE TABLE IF NOT EXISTS SystemSettings (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SettingKey VARCHAR(100) NOT NULL UNIQUE,
    SettingValue TEXT NULL,
    SettingType VARCHAR(50) NOT NULL DEFAULT 'String',
    Description VARCHAR(500) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BackupSettings (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    BackupPath VARCHAR(500) NOT NULL,
    ScheduleType VARCHAR(50) NOT NULL DEFAULT 'Daily',
    ScheduleTime TIME NOT NULL DEFAULT '02:00:00',
    RetentionDays INT DEFAULT 30,
    CompressBackup BOOLEAN DEFAULT 1,
    EncryptBackup BOOLEAN DEFAULT 0,
    EncryptionKey VARCHAR(500) NULL,
    IsActive BOOLEAN DEFAULT 1,
    IsDeleted BOOLEAN DEFAULT 0,
    LastBackupAt DATETIME NULL,
    NextBackupAt DATETIME NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DataMigrations (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL UNIQUE,
    Description VARCHAR(500) NULL,
    SourceType VARCHAR(50) NULL,
    SourceConnectionString VARCHAR(500) NULL,
    TargetType VARCHAR(50) NULL DEFAULT 'MySQL',
    TargetConnectionString VARCHAR(500) NULL,
    TableMappings TEXT NULL,
    ColumnMappings TEXT NULL,
    TransformRules TEXT NULL,
    ScheduleType VARCHAR(50) DEFAULT 'Manual',
    ScheduledAt DATETIME NULL,
    Status VARCHAR(20) DEFAULT 'Pending',
    StartedAt DATETIME NULL,
    CompletedAt DATETIME NULL,
    TotalRecords INT DEFAULT 0,
    ProcessedRecords INT DEFAULT 0,
    FailedRecords INT DEFAULT 0,
    ErrorMessage VARCHAR(2000) NULL,
    LogOutput TEXT NULL,
    RetryCount INT DEFAULT 0,
    MaxRetries INT DEFAULT 3,
    IsScheduled BOOLEAN DEFAULT 0,
    IsActive BOOLEAN DEFAULT 1,
    LastRunAt DATETIME NULL,
    NextRunAt DATETIME NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SuperAdminLogs (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Action VARCHAR(100) NOT NULL,
    EntityName VARCHAR(100) NULL,
    EntityId INT NULL,
    Details TEXT NULL,
    ExecutedByUserId INT NULL,
    ExecutedByUserName VARCHAR(200) NULL,
    IpAddress VARCHAR(50) NULL,
    Status VARCHAR(50) DEFAULT 'Success',
    ErrorMessage VARCHAR(2000) NULL,
    DurationMs INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IX_SuperAdminLogs_User (ExecutedByUserId),
    INDEX IX_SuperAdminLogs_Date (CreatedAt)
) ENGINE=InnoDB;

-- Receipt/Voucher Tables
CREATE TABLE IF NOT EXISTS SaleReceipts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ReceiptNo VARCHAR(50) NOT NULL UNIQUE,
    SaleId INT NOT NULL,
    CustomerId INT NOT NULL,
    ReceiptDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    PaidAmount DECIMAL(18,2) DEFAULT 0,
    BalanceAmount DECIMAL(18,2) DEFAULT 0,
    PaymentMethod VARCHAR(50) NOT NULL DEFAULT 'Cash',
    ReferenceNo VARCHAR(100) NULL,
    Notes VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SaleReceipts_Sale FOREIGN KEY (SaleId) REFERENCES Sales(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_SaleReceipts_Customer FOREIGN KEY (CustomerId) REFERENCES Customers(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SaleReceiptDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SaleReceiptId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    LineTotal DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SaleReceiptDetails_Receipt FOREIGN KEY (SaleReceiptId) REFERENCES SaleReceipts(Id) ON DELETE CASCADE,
    CONSTRAINT FK_SaleReceiptDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PurchaseReceipts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ReceiptNo VARCHAR(50) NOT NULL UNIQUE,
    PurchaseId INT NOT NULL,
    SupplierId INT NOT NULL,
    ReceiptDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    PaidAmount DECIMAL(18,2) DEFAULT 0,
    BalanceAmount DECIMAL(18,2) DEFAULT 0,
    PaymentMethod VARCHAR(50) NOT NULL DEFAULT 'Cash',
    ReferenceNo VARCHAR(100) NULL,
    Notes VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_PurchaseReceipts_Purchase FOREIGN KEY (PurchaseId) REFERENCES Purchases(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_PurchaseReceipts_Supplier FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PurchaseReceiptDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    PurchaseReceiptId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    LineTotal DECIMAL(18,2) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_PurchaseReceiptDetails_Receipt FOREIGN KEY (PurchaseReceiptId) REFERENCES PurchaseReceipts(Id) ON DELETE CASCADE,
    CONSTRAINT FK_PurchaseReceiptDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PaymentVouchers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    VoucherNo VARCHAR(50) NOT NULL UNIQUE,
    VoucherType VARCHAR(50) NOT NULL DEFAULT 'Payment',
    PartyType VARCHAR(50) NOT NULL,
    PartyId INT NOT NULL,
    VoucherDate DATETIME NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentMethod VARCHAR(50) NOT NULL DEFAULT 'Cash',
    ReferenceNo VARCHAR(100) NULL,
    BankName VARCHAR(200) NULL,
    ChequeNo VARCHAR(50) NULL,
    ChequeDate DATETIME NULL,
    Narration VARCHAR(500) NULL,
    Status VARCHAR(50) DEFAULT 'Active',
    CreatedByUserId INT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0
) ENGINE=InnoDB;

-- Stock Transfer Tables
CREATE TABLE IF NOT EXISTS StockTransfers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    TransferNo VARCHAR(50) NOT NULL UNIQUE,
    FromLocationId INT NOT NULL,
    ToLocationId INT NOT NULL,
    TransferDate DATETIME NOT NULL,
    ReceivedDate DATETIME NULL,
    Status VARCHAR(50) DEFAULT 'Pending',
    CreatedByUserId INT NULL,
    ReceivedByUserId INT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StockTransfers_FromLocation FOREIGN KEY (FromLocationId) REFERENCES Locations(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_StockTransfers_ToLocation FOREIGN KEY (ToLocationId) REFERENCES Locations(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS StockTransferDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    StockTransferId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL,
    UnitCost DECIMAL(18,2) NOT NULL,
    LineTotal DECIMAL(18,2) NOT NULL,
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_StockTransferDetails_Transfer FOREIGN KEY (StockTransferId) REFERENCES StockTransfers(Id) ON DELETE CASCADE,
    CONSTRAINT FK_StockTransferDetails_Product FOREIGN KEY (ProductId) REFERENCES Products(Id) ON DELETE RESTRICT
) ENGINE=InnoDB;