-- Migration 005: Add Missing Entity Tables
-- Applied by: DatabaseInitializer / MigrationRunner
-- Description: Creates tables for entity models that had repositories/models but no schema.
-- Covers legacy VO counterparts: Registration (license), RemoteWarehouse (Starman remote sites),
-- Subscription (licensing), DashboardWidget (dashboard). All include EntityBase audit columns.

CREATE TABLE IF NOT EXISTS Registrations (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    LicenseKey VARCHAR(100) NOT NULL UNIQUE,
    CompanyName VARCHAR(200) NOT NULL,
    ContactPerson VARCHAR(100) NULL,
    Email VARCHAR(100) NULL,
    Phone VARCHAR(20) NULL,
    Address VARCHAR(300) NULL,
    RegistrationDate DATETIME NOT NULL,
    ExpiryDate DATETIME NOT NULL,
    MaxUsers INT DEFAULT 1,
    MaxDevices INT DEFAULT 1,
    Status VARCHAR(50) DEFAULT 'Active',
    Notes VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    INDEX IX_Registrations_Status (Status),
    INDEX IX_Registrations_ExpiryDate (ExpiryDate)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RemoteWarehouses (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Code VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(200) NOT NULL,
    ApiUrl VARCHAR(500) NOT NULL,
    ApiKey VARCHAR(200) NULL,
    IsActive BOOLEAN DEFAULT 1,
    LastSyncAt DATETIME NULL,
    ContactInfo VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    INDEX IX_RemoteWarehouses_IsActive (IsActive)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Subscriptions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SubscriptionKey VARCHAR(100) NOT NULL UNIQUE,
    CompanyName VARCHAR(200) NOT NULL,
    ContactPerson VARCHAR(100) NULL,
    Email VARCHAR(100) NULL,
    Phone VARCHAR(20) NULL,
    Address VARCHAR(300) NULL,
    StartDate DATETIME NOT NULL,
    ExpiryDate DATETIME NOT NULL,
    MaxUsers INT DEFAULT 1,
    MaxDevices INT DEFAULT 1,
    MaxLocations INT DEFAULT 1,
    Status VARCHAR(50) DEFAULT 'Active',
    Notes VARCHAR(500) NULL,
    IsActivated BOOLEAN DEFAULT 0,
    ActivatedDate DATETIME NULL,
    ActivatedDeviceId VARCHAR(200) NULL,
    CurrentUserCount INT DEFAULT 0,
    CurrentDeviceCount INT DEFAULT 0,
    CurrentLocationCount INT DEFAULT 0,
    SubscriptionType VARCHAR(50) DEFAULT 'Standard',
    MonthlyPrice DECIMAL(18,2) DEFAULT 0,
    YearlyPrice DECIMAL(18,2) DEFAULT 0,
    BillingCycleDays INT DEFAULT 30,
    LastBillingDate DATETIME NULL,
    NextBillingDate DATETIME NULL,
    PaymentMethod VARCHAR(100) NULL,
    PaymentReference VARCHAR(100) NULL,
    AutoRenew BOOLEAN DEFAULT 1,
    GracePeriodDays INT DEFAULT 7,
    IsTrial BOOLEAN DEFAULT 0,
    TrialDays INT DEFAULT 30,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    INDEX IX_Subscriptions_Status (Status),
    INDEX IX_Subscriptions_ExpiryDate (ExpiryDate)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DashboardWidgets (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    DisplayName VARCHAR(200) NULL,
    Description VARCHAR(500) NULL,
    WidgetType VARCHAR(50) NOT NULL,
    DataSource VARCHAR(50) NOT NULL,
    DataSourceMethod VARCHAR(100) NULL,
    Configuration VARCHAR(2000) NULL,
    ChartType VARCHAR(100) NULL,
    TimeRange VARCHAR(50) DEFAULT 'Last30Days',
    CustomStartDate DATETIME NULL,
    CustomEndDate DATETIME NULL,
    RefreshIntervalMinutes INT DEFAULT 5,
    Width INT DEFAULT 6,
    Height INT DEFAULT 4,
    DisplayOrder INT DEFAULT 0,
    LocationId INT NULL,
    UserId INT NULL,
    IsDefault BOOLEAN DEFAULT 0,
    IsVisible BOOLEAN DEFAULT 1,
    IsEnabled BOOLEAN DEFAULT 1,
    Size VARCHAR(50) DEFAULT 'Medium',
    Icon VARCHAR(100) NULL,
    ColorScheme VARCHAR(50) NULL,
    CustomCssClass VARCHAR(500) NULL,
    MaxRecords INT DEFAULT 50,
    GroupBy VARCHAR(100) NULL,
    SortBy VARCHAR(100) NULL,
    SortDirection VARCHAR(10) DEFAULT 'DESC',
    ShowHeader BOOLEAN DEFAULT 1,
    ShowFooter BOOLEAN DEFAULT 0,
    AllowExport BOOLEAN DEFAULT 1,
    AllowDrillDown BOOLEAN DEFAULT 0,
    DrillDownUrl VARCHAR(200) NULL,
    DrillDownParameters VARCHAR(500) NULL,
    LastRefreshedAt DATETIME NULL,
    RefreshCount INT DEFAULT 0,
    LastError VARCHAR(500) NULL,
    HasError BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_DashboardWidgets_Location FOREIGN KEY (LocationId) REFERENCES Locations (Id) ON DELETE SET NULL,
    CONSTRAINT FK_DashboardWidgets_User FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE SET NULL,
    INDEX IX_DashboardWidgets_UserId (UserId),
    INDEX IX_DashboardWidgets_LocationId (LocationId),
    INDEX IX_DashboardWidgets_WidgetType (WidgetType)
) ENGINE=InnoDB;
