-- Migration 006: Align Schema With Entity Models
-- Applied by: DatabaseInitializer / MigrationRunner
-- Description:
--   1) Adds EntityBase audit columns (CreatedAt/UpdatedAt/CreatedBy/UpdatedBy/IsDeleted) where missing.
--   2) Adds model/repository-required columns missing from early tables.
--   3) Rebuilds tables whose original shape conflicts with their entity/repository contracts:
--      SystemSettings, BackupSettings, SuperAdminLogs, PaymentVouchers,
--      SaleReceipts(+Details), PurchaseReceipts(+Details).
--      Safe: those tables could never be written by the application (every repository INSERT
--      referenced columns the old tables did not have), so they contain no usable business data.
-- All steps are idempotent and re-runnable.

-----------------------------------------------------------------------------
-- A. EntityBase audit columns (CreatedBy / UpdatedBy)
-----------------------------------------------------------------------------
-- Categories.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Categories' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Categories ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Categories.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Categories' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Categories ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Units.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Units' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Units ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Units.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Units' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Units ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- `Groups`.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = '`Groups`' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE `Groups` ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- `Groups`.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = '`Groups`' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE `Groups` ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Currencies.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Currencies' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Currencies ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Currencies.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Currencies' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Currencies ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Taxes.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Taxes' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Taxes ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Taxes.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Taxes' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Taxes ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Discounts.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Discounts' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Discounts ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Discounts.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Discounts' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Discounts ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Locations.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Locations' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Locations ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Locations.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Locations' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Locations ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Companies.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Companies' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Companies ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Companies.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Companies' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Companies ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Users.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Users' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Users ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Users.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Users' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Users ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Roles.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Roles' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Roles ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Roles.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Roles' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Roles ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- EmailSettings.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'EmailSettings' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE EmailSettings ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- EmailSettings.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'EmailSettings' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE EmailSettings ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Suppliers.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Suppliers' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Suppliers ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Suppliers.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Suppliers' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Suppliers ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ExpenseTypes.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ExpenseTypes' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE ExpenseTypes ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ExpenseTypes.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ExpenseTypes' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE ExpenseTypes ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Themes.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Themes' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Themes ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Themes.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Themes' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Themes ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Languages.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Languages' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Languages ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Languages.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Languages' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Languages ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ReportMenus.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ReportMenus' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE ReportMenus ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ReportMenus.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ReportMenus' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE ReportMenus ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SaleTemps.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleTemps' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE SaleTemps ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SaleTemps.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleTemps' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE SaleTemps ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SaleTempDetails.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleTempDetails' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE SaleTempDetails ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SaleTempDetails.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleTempDetails' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE SaleTempDetails ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Assemblies.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Assemblies' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Assemblies ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Assemblies.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Assemblies' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Assemblies ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- AssemblyDetails.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'AssemblyDetails' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE AssemblyDetails ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- AssemblyDetails.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'AssemblyDetails' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE AssemblyDetails ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SalePriceHistories.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SalePriceHistories' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE SalePriceHistories ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SalePriceHistories.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SalePriceHistories' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE SalePriceHistories ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- LinkedStocks.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LinkedStocks' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE LinkedStocks ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- LinkedStocks.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LinkedStocks' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE LinkedStocks ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Purchases.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Purchases' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Purchases ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Purchases.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Purchases' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Purchases ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PurchaseDetails.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseDetails' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE PurchaseDetails ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PurchaseDetails.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseDetails' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE PurchaseDetails ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PurchaseReturns.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseReturns' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE PurchaseReturns ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PurchaseReturns.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseReturns' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE PurchaseReturns ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PurchaseReturnDetails.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseReturnDetails' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE PurchaseReturnDetails ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PurchaseReturnDetails.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseReturnDetails' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE PurchaseReturnDetails ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- CustomerOutstandings.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'CustomerOutstandings' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE CustomerOutstandings ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- CustomerOutstandings.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'CustomerOutstandings' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE CustomerOutstandings ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SupplierOutstandings.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SupplierOutstandings' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE SupplierOutstandings ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SupplierOutstandings.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SupplierOutstandings' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE SupplierOutstandings ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Payments.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Payments' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Payments ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Payments.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Payments' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Payments ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Expenses.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Expenses ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Expenses.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Expenses' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Expenses ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Invoices.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Invoices' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Invoices ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Invoices.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Invoices' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Invoices ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SalesReturns.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SalesReturns' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE SalesReturns ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SalesReturns.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SalesReturns' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE SalesReturns ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SalesReturnDetails.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SalesReturnDetails' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE SalesReturnDetails ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SalesReturnDetails.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SalesReturnDetails' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE SalesReturnDetails ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- LicenseInfos.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LicenseInfos' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE LicenseInfos ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- LicenseInfos.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'LicenseInfos' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE LicenseInfos ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- DeviceInfos.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DeviceInfos' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE DeviceInfos ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- DeviceInfos.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DeviceInfos' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE DeviceInfos ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- DeviceRequests.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DeviceRequests' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE DeviceRequests ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- DeviceRequests.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DeviceRequests' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE DeviceRequests ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PcClients.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PcClients' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE PcClients ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PcClients.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PcClients' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE PcClients ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- MobileClients.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MobileClients' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE MobileClients ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- MobileClients.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MobileClients' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE MobileClients ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- AppInfos.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'AppInfos' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE AppInfos ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- AppInfos.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'AppInfos' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE AppInfos ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PCUpdates.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PCUpdates' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE PCUpdates ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PCUpdates.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PCUpdates' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE PCUpdates ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ClientUpdateRequests.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ClientUpdateRequests' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE ClientUpdateRequests ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ClientUpdateRequests.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ClientUpdateRequests' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE ClientUpdateRequests ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarStockTransferReceiveds.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarStockTransferReceiveds' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarStockTransferReceiveds ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarStockTransferReceiveds.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarStockTransferReceiveds' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarStockTransferReceiveds ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarSalePriceTransfers.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarSalePriceTransfers' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarSalePriceTransfers ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarSalePriceTransfers.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarSalePriceTransfers' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarSalePriceTransfers ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarCashFlowReports.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarCashFlowReports' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarCashFlowReports ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarCashFlowReports.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarCashFlowReports' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarCashFlowReports ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarProfitLossReports.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarProfitLossReports' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarProfitLossReports ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarProfitLossReports.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarProfitLossReports' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarProfitLossReports ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarStockBalanceReports.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarStockBalanceReports' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarStockBalanceReports ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarStockBalanceReports.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarStockBalanceReports' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarStockBalanceReports ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarReorderReports.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarReorderReports' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarReorderReports ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarReorderReports.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarReorderReports' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarReorderReports ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarOutstandingReports.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarOutstandingReports' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarOutstandingReports ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StarOutstandingReports.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StarOutstandingReports' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StarOutstandingReports ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- IssueHeaders.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'IssueHeaders' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE IssueHeaders ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- IssueHeaders.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'IssueHeaders' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE IssueHeaders ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockTransfers.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockTransfers' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StockTransfers ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockTransfers.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockTransfers' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StockTransfers ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockTransferDetails.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockTransferDetails' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StockTransferDetails ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockTransferDetails.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockTransferDetails' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StockTransferDetails ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockMovements.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockMovements' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StockMovements ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockMovements.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockMovements' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StockMovements ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockMovementDetails.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockMovementDetails' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE StockMovementDetails ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockMovementDetails.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockMovementDetails' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE StockMovementDetails ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- DataMigrations.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DataMigrations' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE DataMigrations ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- DataMigrations.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'DataMigrations' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE DataMigrations ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ChangeDateLogs.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ChangeDateLogs' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE ChangeDateLogs ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ChangeDateLogs.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ChangeDateLogs' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE ChangeDateLogs ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-----------------------------------------------------------------------------
-- A2. Timestamp / soft-delete gaps (Sales, SaleDetails, UserRoles, MenuRoles, ChangeDateLogs)
-----------------------------------------------------------------------------
-- Sales.CreatedAt
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Sales' AND COLUMN_NAME = 'CreatedAt') > 0, 'SELECT 1', 'ALTER TABLE Sales ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Sales.UpdatedAt
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Sales' AND COLUMN_NAME = 'UpdatedAt') > 0, 'SELECT 1', 'ALTER TABLE Sales ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Sales.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Sales' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE Sales ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Sales.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Sales' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE Sales ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SaleDetails.CreatedAt
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleDetails' AND COLUMN_NAME = 'CreatedAt') > 0, 'SELECT 1', 'ALTER TABLE SaleDetails ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SaleDetails.UpdatedAt
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleDetails' AND COLUMN_NAME = 'UpdatedAt') > 0, 'SELECT 1', 'ALTER TABLE SaleDetails ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SaleDetails.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleDetails' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE SaleDetails ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SaleDetails.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleDetails' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE SaleDetails ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- UserRoles.CreatedAt
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'UserRoles' AND COLUMN_NAME = 'CreatedAt') > 0, 'SELECT 1', 'ALTER TABLE UserRoles ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- UserRoles.UpdatedAt
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'UserRoles' AND COLUMN_NAME = 'UpdatedAt') > 0, 'SELECT 1', 'ALTER TABLE UserRoles ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- UserRoles.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'UserRoles' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE UserRoles ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- UserRoles.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'UserRoles' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE UserRoles ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- MenuRoles.CreatedAt
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MenuRoles' AND COLUMN_NAME = 'CreatedAt') > 0, 'SELECT 1', 'ALTER TABLE MenuRoles ADD COLUMN CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- MenuRoles.UpdatedAt
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MenuRoles' AND COLUMN_NAME = 'UpdatedAt') > 0, 'SELECT 1', 'ALTER TABLE MenuRoles ADD COLUMN UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- MenuRoles.CreatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MenuRoles' AND COLUMN_NAME = 'CreatedBy') > 0, 'SELECT 1', 'ALTER TABLE MenuRoles ADD COLUMN CreatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- MenuRoles.UpdatedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'MenuRoles' AND COLUMN_NAME = 'UpdatedBy') > 0, 'SELECT 1', 'ALTER TABLE MenuRoles ADD COLUMN UpdatedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- ChangeDateLogs.IsDeleted
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'ChangeDateLogs' AND COLUMN_NAME = 'IsDeleted') > 0, 'SELECT 1', 'ALTER TABLE ChangeDateLogs ADD COLUMN IsDeleted BOOLEAN DEFAULT 0'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-----------------------------------------------------------------------------
-- B. Model-required columns missing from tables
-----------------------------------------------------------------------------
-- Products.LastAdjustment
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Products' AND COLUMN_NAME = 'LastAdjustment') > 0, 'SELECT 1', 'ALTER TABLE Products ADD COLUMN LastAdjustment DATETIME NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Products.AdjustedBy
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Products' AND COLUMN_NAME = 'AdjustedBy') > 0, 'SELECT 1', 'ALTER TABLE Products ADD COLUMN AdjustedBy INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- Products.AdjustmentReason
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'Products' AND COLUMN_NAME = 'AdjustmentReason') > 0, 'SELECT 1', 'ALTER TABLE Products ADD COLUMN AdjustmentReason VARCHAR(500) NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockMovements.ProductId
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockMovements' AND COLUMN_NAME = 'ProductId') > 0, 'SELECT 1', 'ALTER TABLE StockMovements ADD COLUMN ProductId INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockMovements.Quantity
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockMovements' AND COLUMN_NAME = 'Quantity') > 0, 'SELECT 1', 'ALTER TABLE StockMovements ADD COLUMN Quantity INT NOT NULL DEFAULT 0'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockMovements.IsActive
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockMovements' AND COLUMN_NAME = 'IsActive') > 0, 'SELECT 1', 'ALTER TABLE StockMovements ADD COLUMN IsActive BOOLEAN DEFAULT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PurchaseDetails.ReceivedQuantity
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseDetails' AND COLUMN_NAME = 'ReceivedQuantity') > 0, 'SELECT 1', 'ALTER TABLE PurchaseDetails ADD COLUMN ReceivedQuantity INT NOT NULL DEFAULT 0'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- PurchaseReturnDetails.ReceivedQuantity
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseReturnDetails' AND COLUMN_NAME = 'ReceivedQuantity') > 0, 'SELECT 1', 'ALTER TABLE PurchaseReturnDetails ADD COLUMN ReceivedQuantity INT NOT NULL DEFAULT 0'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockTransferDetails.ReceivedQuantity
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockTransferDetails' AND COLUMN_NAME = 'ReceivedQuantity') > 0, 'SELECT 1', 'ALTER TABLE StockTransferDetails ADD COLUMN ReceivedQuantity INT NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockTransferDetails.SerialNumber
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'StockTransferDetails' AND COLUMN_NAME = 'SerialNumber') > 0, 'SELECT 1', 'ALTER TABLE StockTransferDetails ADD COLUMN SerialNumber VARCHAR(50) NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- SalePriceHistories.Reason
SET @sql := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SalePriceHistories' AND COLUMN_NAME = 'Reason') > 0, 'SELECT 1', 'ALTER TABLE SalePriceHistories ADD COLUMN Reason VARCHAR(500) NULL'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- StockTransferDetails: UnitCost/LineTotal are NOT NULL without defaults but the entity
-- (and generic INSERT) do not supply them; give safe defaults. (Re-applying is a no-op.)
ALTER TABLE StockTransferDetails MODIFY COLUMN UnitCost DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE StockTransferDetails MODIFY COLUMN LineTotal DECIMAL(18,2) NOT NULL DEFAULT 0;

-----------------------------------------------------------------------------
-- C. Rebuild legacy-shaped tables to match entity/repository contracts
--    (guarded: runs only while the legacy column signature is detected)
-----------------------------------------------------------------------------
-- Evaluate rebuild flags (1 = legacy shape detected)
SET @rb_sys := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SystemSettings' AND COLUMN_NAME = 'Key') = 0, 1, 0));
SET @rb_bak := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'BackupSettings' AND COLUMN_NAME = 'Name') = 0, 1, 0));
SET @rb_sal := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SuperAdminLogs' AND COLUMN_NAME = 'Module') = 0, 1, 0));
SET @rb_pv  := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PaymentVouchers' AND COLUMN_NAME = 'PaymentType') = 0, 1, 0));
SET @rb_sr  := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'SaleReceipts' AND COLUMN_NAME = 'SaleDate') = 0, 1, 0));
SET @rb_pr  := (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'PurchaseReceipts' AND COLUMN_NAME = 'PurchaseDate') = 0, 1, 0));

-- Drops (children first)
SET @sql := (SELECT IF(@rb_sr = 1, 'DROP TABLE IF EXISTS SaleReceiptDetails', 'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(@rb_sr = 1, 'DROP TABLE IF EXISTS SaleReceipts', 'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(@rb_pr = 1, 'DROP TABLE IF EXISTS PurchaseReceiptDetails', 'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(@rb_pr = 1, 'DROP TABLE IF EXISTS PurchaseReceipts', 'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(@rb_pv = 1, 'DROP TABLE IF EXISTS PaymentVouchers', 'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(@rb_sal = 1, 'DROP TABLE IF EXISTS SuperAdminLogs', 'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(@rb_bak = 1, 'DROP TABLE IF EXISTS BackupSettings', 'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql := (SELECT IF(@rb_sys = 1, 'DROP TABLE IF EXISTS SystemSettings', 'SELECT 1'));
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- Creates (plain CREATE TABLE IF NOT EXISTS; skipped automatically when table kept its new shape)
CREATE TABLE IF NOT EXISTS SystemSettings (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    `Key` VARCHAR(100) NOT NULL,
    `Value` VARCHAR(500) NOT NULL DEFAULT '',
    Category VARCHAR(50) NOT NULL DEFAULT '',
    Description VARCHAR(200) NOT NULL DEFAULT '',
    DataType VARCHAR(20) NOT NULL DEFAULT 'String',
    IsSystem BOOLEAN DEFAULT 0,
    IsReadOnly BOOLEAN DEFAULT 0,
    IsActive BOOLEAN DEFAULT 1,
    ValidationRules VARCHAR(500) NOT NULL DEFAULT '',
    DefaultValue VARCHAR(1000) NOT NULL DEFAULT '',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    UNIQUE KEY UQ_SystemSettings_Key (`Key`),
    INDEX IX_SystemSettings_Category (Category)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BackupSettings (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(500) NOT NULL DEFAULT '',
    Frequency VARCHAR(20) NOT NULL DEFAULT 'Daily',
    ExecutionTime TIME NOT NULL DEFAULT '02:00:00',
    RetentionDays INT DEFAULT 30,
    BackupPath VARCHAR(500) NOT NULL DEFAULT '',
    StorageType VARCHAR(20) NOT NULL DEFAULT 'Local',
    RemoteConnectionString VARCHAR(500) NOT NULL DEFAULT '',
    IncludeDatabase BOOLEAN DEFAULT 1,
    IncludeFiles BOOLEAN DEFAULT 1,
    IncludeLogs BOOLEAN DEFAULT 0,
    IncludeImages BOOLEAN DEFAULT 1,
    CompressBackup BOOLEAN DEFAULT 1,
    EncryptBackup BOOLEAN DEFAULT 0,
    EncryptionPassword VARCHAR(100) NOT NULL DEFAULT '',
    SendNotificationOnSuccess BOOLEAN DEFAULT 1,
    SendNotificationOnFailure BOOLEAN DEFAULT 1,
    NotificationEmails VARCHAR(500) NOT NULL DEFAULT '',
    IsActive BOOLEAN DEFAULT 1,
    LastRunAt DATETIME NULL,
    NextRunAt DATETIME NULL,
    LastStatus VARCHAR(50) NOT NULL DEFAULT '',
    LastErrorMessage VARCHAR(1000) NOT NULL DEFAULT '',
    MaxParallelJobs INT DEFAULT 1,
    TimeoutMinutes INT DEFAULT 60,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    UNIQUE KEY UQ_BackupSettings_Name (Name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SuperAdminLogs (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Action VARCHAR(50) NOT NULL DEFAULT '',
    EntityType VARCHAR(100) NOT NULL DEFAULT '',
    EntityId INT NULL,
    PerformedBy VARCHAR(100) NOT NULL DEFAULT '',
    PerformedByUserId INT NOT NULL,
    IpAddress VARCHAR(50) NOT NULL DEFAULT '',
    UserAgent VARCHAR(500) NOT NULL DEFAULT '',
    BeforeState TEXT NULL,
    AfterState TEXT NULL,
    Module VARCHAR(100) NOT NULL DEFAULT '',
    Severity VARCHAR(20) NOT NULL DEFAULT 'Info',
    Description VARCHAR(2000) NOT NULL DEFAULT '',
    IsSensitive BOOLEAN DEFAULT 0,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SuperAdminLogs_PerformedBy FOREIGN KEY (PerformedByUserId) REFERENCES Users (Id) ON DELETE RESTRICT,
    INDEX IX_SuperAdminLogs_PerformedByUserId (PerformedByUserId),
    INDEX IX_SuperAdminLogs_Module (Module),
    INDEX IX_SuperAdminLogs_CreatedAt (CreatedAt)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PaymentVouchers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    VoucherNo VARCHAR(50) NOT NULL,
    PaymentType VARCHAR(50) NOT NULL DEFAULT 'Customer',
    CustomerId INT NULL,
    SupplierId INT NULL,
    SaleId INT NULL,
    PurchaseId INT NULL,
    OutstandingId INT NULL,
    VoucherDate DATETIME NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Method VARCHAR(20) NOT NULL DEFAULT 'Cash',
    ReferenceNo VARCHAR(50) NULL,
    BankName VARCHAR(100) NULL,
    ChequeNo VARCHAR(50) NULL,
    ChequeDate DATETIME NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Cleared',
    ReceivedByUserId INT NULL,
    ReceivedAt DATETIME NULL,
    Notes VARCHAR(500) NULL,
    TerminalId VARCHAR(20) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_PaymentVouchers_Customer FOREIGN KEY (CustomerId) REFERENCES Customers (Id) ON DELETE SET NULL,
    CONSTRAINT FK_PaymentVouchers_Supplier FOREIGN KEY (SupplierId) REFERENCES Suppliers (Id) ON DELETE SET NULL,
    CONSTRAINT FK_PaymentVouchers_Sale FOREIGN KEY (SaleId) REFERENCES Sales (Id) ON DELETE SET NULL,
    CONSTRAINT FK_PaymentVouchers_Purchase FOREIGN KEY (PurchaseId) REFERENCES Purchases (Id) ON DELETE SET NULL,
    UNIQUE KEY UQ_PaymentVouchers_VoucherNo (VoucherNo),
    INDEX IX_PaymentVouchers_CustomerId (CustomerId),
    INDEX IX_PaymentVouchers_SupplierId (SupplierId),
    INDEX IX_PaymentVouchers_SaleId (SaleId),
    INDEX IX_PaymentVouchers_PurchaseId (PurchaseId),
    INDEX IX_PaymentVouchers_VoucherDate (VoucherDate),
    INDEX IX_PaymentVouchers_Status (Status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SaleReceipts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ReceiptNo VARCHAR(50) NOT NULL,
    SaleId INT NOT NULL,
    CustomerName VARCHAR(150) NULL,
    CustomerPhone VARCHAR(20) NULL,
    SaleDate DATETIME NOT NULL,
    PaymentMethod VARCHAR(50) NULL,
    SubTotal DECIMAL(18,2) DEFAULT 0,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    TotalAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
    PaidAmount DECIMAL(18,2) DEFAULT 0,
    ChangeAmount DECIMAL(18,2) DEFAULT 0,
    Notes VARCHAR(500) NULL,
    PrintedByUserId INT NULL,
    PrintedAt DATETIME NULL,
    PrintCount INT DEFAULT 0,
    TerminalId VARCHAR(20) NULL,
    IsReprint BOOLEAN DEFAULT 0,
    FooterText VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SaleReceipts_Sale FOREIGN KEY (SaleId) REFERENCES Sales (Id) ON DELETE RESTRICT,
    UNIQUE KEY UQ_SaleReceipts_ReceiptNo (ReceiptNo),
    INDEX IX_SaleReceipts_SaleId (SaleId),
    INDEX IX_SaleReceipts_SaleDate (SaleDate)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SaleReceiptDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SaleReceiptId INT NOT NULL,
    ProductSku VARCHAR(50) NULL,
    ProductName VARCHAR(200) NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18,2) NOT NULL,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    LineTotal DECIMAL(18,2) NOT NULL,
    UnitOfMeasure VARCHAR(50) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_SaleReceiptDetails_Receipt FOREIGN KEY (SaleReceiptId) REFERENCES SaleReceipts (Id) ON DELETE CASCADE,
    INDEX IX_SaleReceiptDetails_SaleReceiptId (SaleReceiptId)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PurchaseReceipts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ReceiptNo VARCHAR(50) NOT NULL,
    PurchaseId INT NOT NULL,
    SupplierName VARCHAR(150) NULL,
    SupplierPhone VARCHAR(20) NULL,
    PurchaseDate DATETIME NOT NULL,
    PaymentMethod VARCHAR(50) NULL,
    SubTotal DECIMAL(18,2) DEFAULT 0,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    TotalAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
    PaidAmount DECIMAL(18,2) DEFAULT 0,
    ChangeAmount DECIMAL(18,2) DEFAULT 0,
    Notes VARCHAR(500) NULL,
    PrintedByUserId INT NULL,
    PrintedAt DATETIME NULL,
    PrintCount INT DEFAULT 0,
    TerminalId VARCHAR(20) NULL,
    IsReprint BOOLEAN DEFAULT 0,
    FooterText VARCHAR(500) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_PurchaseReceipts_Purchase FOREIGN KEY (PurchaseId) REFERENCES Purchases (Id) ON DELETE RESTRICT,
    UNIQUE KEY UQ_PurchaseReceipts_ReceiptNo (ReceiptNo),
    INDEX IX_PurchaseReceipts_PurchaseId (PurchaseId),
    INDEX IX_PurchaseReceipts_PurchaseDate (PurchaseDate)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PurchaseReceiptDetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    PurchaseReceiptId INT NOT NULL,
    ProductSku VARCHAR(50) NULL,
    ProductName VARCHAR(200) NOT NULL,
    Quantity INT NOT NULL,
    ReceivedQuantity INT NOT NULL DEFAULT 0,
    UnitPrice DECIMAL(18,2) NOT NULL,
    DiscountAmount DECIMAL(18,2) DEFAULT 0,
    TaxAmount DECIMAL(18,2) DEFAULT 0,
    LineTotal DECIMAL(18,2) NOT NULL,
    UnitOfMeasure VARCHAR(50) NULL,
    BatchNumber VARCHAR(50) NULL,
    ExpiryDate DATETIME NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CreatedBy INT NULL,
    UpdatedBy INT NULL,
    IsDeleted BOOLEAN DEFAULT 0,
    CONSTRAINT FK_PurchaseReceiptDetails_Receipt FOREIGN KEY (PurchaseReceiptId) REFERENCES PurchaseReceipts (Id) ON DELETE CASCADE,
    INDEX IX_PurchaseReceiptDetails_PurchaseReceiptId (PurchaseReceiptId)
) ENGINE=InnoDB;

